name: Read Json Object Values

on:
  push:
    branches: 
      - main
      
jobs:

  extract-keys:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Extract and log the JSON key-values.
      run: |
        keys_and_values=$(echo ${{ secrets.JSON_VALUE }} | jq -r 'to_entries[] | "\(.key)=\(.value)"')
        for key_value in $keys_and_values; do
          echo $key_value
        done
        
    - name: Extract value only
      run: |
        values=$(echo ${{ secrets.JSON_VALUE }} | jq -r 'to_entries[] | "\(.value)"')
        for value in $values; do 
          echo $value
        done
        
